### PR TITLE
Add VoxelMap Fixes

### PR DESCRIPTION
**Pull request by glowredman**
- Correct the Y coordinate being displayed under the minimap (was always one to high)
- Remove reflection
- Add NPE protection when loading chunk data

Also reorganized `dependencies.gradle` to be in alphabetical order and use `deobfCurse`.

### CODE REVIEW

**Comment by bombcar** [comment]
build is crashing on inability to download something, works locally so I suspect I have it in my cache

**Comment by glowredman** [comment]
[java.net.SocketException: Connection reset by peer](https://github.com/GTNewHorizons/Hodgepodge/actions/runs/6775603640/job/18415811085?pr=275#step:7:498)... Works locally for me, can you try it locally @bombcar ?

**Comment by bombcar** [comment]
Weird your other PR is happy but this one still dies

**Comment by Dream-Master** [comment]
```java.net.SocketException: Connection reset by peer
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:431)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:451)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:837)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1047)
	at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:271)
	at java.base/sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:89)
	at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:646)
	at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:[529](https://github.com/GTNewHorizons/Hodgepodge/actions/runs/6775603640/job/18417959729?pr=275#step:7:530))
	at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:112)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:258)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:448)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at com.github.parker8283.bon2.util.DownloadUtils.connectHttpWithRedirects(DownloadUtils.java:32)
	at com.github.parker8283.bon2.util.DownloadUtils.downloadEtag(DownloadUtils.java:70)
	at com.github.parker8283.bon2.util.DownloadUtils.downloadEtag(DownloadUtils.java:54)
	at com.github.parker8283.bon2.util.MinecraftVersions.findFromLauncherManifest(MinecraftVersions.java:67)
	at com.github.parker8283.bon2.util.MinecraftVersions.getKnownVersions(MinecraftVersions.java:32)
	at com.github.parker8283.bon2.util.MinecraftVersions.getKnownVersions(MinecraftVersions.java:25)
	at com.github.parker8283.bon2.BON2.parseArgs(BON2.java:103)
	at com.github.parker8283.bon2.BON2.main(BON2.java:37)
zip END header not found
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1649)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1657)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1495)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1457)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:253)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:182)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:196)
	at com.github.parker8283.bon2.util.IOUtils.getZipData(IOUtils.java:69)
	at com.github.parker8283.bon2.BON2Impl.loadMappings(BON2Impl.java:78)
	at com.github.parker8283.bon2.BON2Impl.loadMappings(BON2Impl.java:72)
	at com.github.parker8283.bon2.BON2Impl.remap(BON2Impl.java:36)
	at com.github.parker8283.bon2.BON2.parseArgs(BON2.java:140)
	at com.github.parker8283.bon2.BON2.main(BON2.java:37)
Closing Git repo: /home/runner/work/Hodgepodge/Hodgepodge/.git```

**Comment by glowredman** [comment]
> Weird your other PR is happy but this one still dies

The other PR doesn't have the code I added to `dependencies.gradle` in this PR.

There seem to be two problems and I don't know if they're related:
1. [java.net.SocketException: Connection reset by peer](https://github.com/GTNewHorizons/Hodgepodge/actions/runs/6775603640/job/18415811085?pr=275#step:7:498) when trying to get the version manifest from https://launchermeta.mojang.com/mc/game/version_manifest.json - this one I get locally too.
2. [java.util.zip.ZipException: zip END header not found](https://github.com/GTNewHorizons/Hodgepodge/actions/runs/6775603640/job/18417959729?pr=275#step:7:525) - which I don't get locally.

I'll debug this further tomorrow.

**Comment by glowredman** [comment]
The problem was [these two lines](https://github.com/GTNewHorizons/Hodgepodge/pull/275/commits/15f3629ca29af9d280185c28d9a6e8f2073d758a#diff-d979b641bd0ea7c9da3fe113f9657636df1002652c75042cfe3b5203da064215R55-R56) missing...

**Review by Caedis — APPROVED** [review]

**Pull request merged**
