### PR TITLE
Add harvest tool to BOP Flesh

### PR DESCRIPTION
**Pull request by Caedis**
Mixin where the blocks are registered so more can be added in the future if needed without creating more mixins

image

### CODE REVIEW

**Review by glowredman — CHANGES_REQUESTED** [review]
There is no need for this to be a mixin. Most methods in the `Block` class are public and can be called from whereever.

**Comment by Caedis** [comment]
Then how should it be done then?

**Comment by glowredman** [comment]
During init, get the block instance and call `setHarvestLevel` on it. Make sure to check first if BOP is loaded and if the fix is enabled in the config. You can get the block instance via the GameRegistry or directly via the `BOPCBlocks` class (if you do the latter, you need to make sure to move the code to a class which is only loaded when BOP is present).

**Comment by Alexdoru** [comment]
> Then how should it be done then?

probably in the NH coremod

**Comment by bombcar** [comment]
Is it possible to have this particular "flesh" be harvestable with something more thematic, like the sword or machete?

**Comment by Alastors** [comment]
> Is it possible to have this particular "flesh" be harvestable with something more thematic, like the sword or machete?
> 
> 
> 
> 

Personally I was thinking sheers

**Comment by Caedis** [comment]
The only tool classes are pick, axe, and shovel.

**Comment by Caedis** [comment]
Dream was initially thinking using a knife, but that would be interesting to code for

**Comment by Dream-Master** [comment]
> > Is it possible to have this particular "flesh" be harvestable with something more thematic, like the sword or machete?
> 
> Personally I was thinking sheers

i thought first a knife or  a butcher knife is funny but it is to much hassle to code so use a normal tool would be enough.

**Comment by Caedis** [comment]
Moving to NHCoreMod

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/747

**Pull request closed without merging**
