### PR TITLE
Add modded Block/Item/Entity Stats

### PR DESCRIPTION
**Pull request by glowredman**
Block/Items stats are registered by injecting in the GameRegistry methods which register them. Entity stats are registered when the server started. The stat arrays for blocks/items are remapped when the block/item ids change.
Note: block/item stats may not work depending on how the mods override certain functions. This affects craft stats the most.

Other changes:
- Move Mixins for FML into their own package
- Use `@WrapWithCondition` v2
- Address some warnings regarding generics
- Sort Entity stats lexicographically (can be disabled in the config)

### CODE REVIEW

**Comment by Caedis** [comment]
How are you handling if a mod manually adds their items to the stat list?

**Comment by Caedis** [comment]
Needs error checking
image

**Review by Caedis — CHANGES_REQUESTED** [review]
Was not tested in full pack; needs error handling

**Comment by glowredman** [comment]
@Caedis Item/Block stats are registered during `GameRegistry.registerItem()` / `GameRegistry.registerBlock()`, so if another mod adds stats for some items/blocks, it will override those added by HP. The stat IDs will most likely be different.
Entity stats are added on `FMLServerStartedEvent`, so other mods most likely have added their stats by then. HP respects that and won't add duplicate stats. An exception is NEI, which adds spawn eggs for Snowmen and Iron Golems. It does so after that event. I added a mod check to suppress NEI's behaviour when HP is loaded and the tweak is enabled.

**Comment by Pxx500** [comment]
Error while changing from MP to SP
image

**Comment by Dream-Master** [comment]
If no one approve this very soon I will merge it. It’s on zeta for a while and I get no negative feedback.

**Comment by Dream-Master** [comment]
@Caedis it is on zeta formore than 4 weeks. So it is tested in full pack

**Review by ah-OOG-ah — APPROVED** [review]

**Pull request merged**
