### PR TITLE
Fix broken tile entity lighting caused by Thaumcraft's advanced alchemical furnace

### PR DESCRIPTION
**Pull request by UnderscoreKilburn**
Fixes GTNewHorizons/GT-New-Horizons-Modpack#15066
This seemed to be caused by the way the fire effect on a powered advanced alchemical furnace is rendered, it disables lighting then reenables it, but also resets a bunch of lighting related parameters in the process, causing all tile entities after it to be rendered with incorrect lighting.

Here's a before/after for comparison:
comparison

### CODE REVIEW

**Comment by Glease** [comment]
FYI I found this fix quite interesting and should reach other 1.7.10 players. I've pulled the idea into TC4Tweaks 1.5.20. Like any other mixin towards tc4 that has been merged into tc4tweaks, it has been converted to asm and thus no code is actually taken. As a token of gratitude, I've added you to the special thanks section on my curseforge project page.

**Comment by Dream-Master** [comment]
so this change is no longer needed here ? @Glease

**Comment by Glease** [comment]
well merging won't hurt. My comment above is mostly to thank the author for his discovery

**Comment by Dream-Master** [comment]
@Glease if this is in your mod can we close this?

**Pull request closed without merging**
