### PR TITLE
Prevents the inventory from shifting when the player has active potion effects

### PR DESCRIPTION
**Pull request by Alexdoru**
works both in dev and in full pack

### CODE REVIEW

**Comment by vlaetansky** [comment]
I am not sure why would you make half of it with ASM? I guess the same can be achieved with Mixins and we should obviously prioritize them instead.

**Comment by Glease** [comment]
@vlaetansky He can't get it to work with mixin. Didn't look why though.

**Comment by Alexdoru** [comment]
> I am not sure why would you make half of it with ASM? I guess the same can be achieved with Mixins and we should obviously prioritize them instead.

because I first tried with mixins and they were crashing, so I moved to ASM for the mixins that weren't working

**Comment by Alexdoru** [comment]
the mixins were crashing in full pack but working in dev, I don't know why

**Comment by vlaetansky** [comment]
Probably it's worth fixing it instead of adding another bunch of ASM, can you push Mixins so anyone can pull the branch and test it out?

**Review by eigenraven — DISMISSED** [review]

**Comment by Alexdoru** [comment]
I commited a full mixin implementation here https://github.com/Alexdoru/Hodgepodge/commit/8f91d0271ebd2d78fa4c517458b083da49cab87a

it works in dev but it crashed in the full pack with this error : 
[crash-2022-09-01_16.17.38-client.txt](https://github.com/GTNewHorizons/Hodgepodge/files/9470645/crash-2022-09-01_16.17.3
[fml-client-latest.log](https://github.com/GTNewHorizons/Hodgepodge/files/9470652/fml-client-latest.log)
8-client.txt)

**Comment by Alexdoru** [comment]
> I commited a full mixin implementation here [Alexdoru@8f91d02](https://github.com/Alexdoru/Hodgepodge/commit/8f91d0271ebd2d78fa4c517458b083da49cab87a)
> 
> it works in dev but it crashed in the full pack with this error :
> 
> [crash-2022-09-01_16.17.38-client.txt](https://github.com/GTNewHorizons/Hodgepodge/files/9470706/crash-2022-09-01_16.17.38-client.txt)
> 
> [fml-client-latest.log](https://github.com/GTNewHorizons/Hodgepodge/files/9470708/fml-client-latest.log)

so can I make another pull request with mixins and just ASM for the one problematic mixin ?

**Comment by Glease** [comment]
wrong jar loaded

It loaded a wrong jar.

**Pull request closed without merging**
