### PR TITLE
Remove 2MB chunk size limit

### PR DESCRIPTION
**Pull request by eigenraven**
Ports <https://github.com/CrucibleMC/Crucible/blob/staging/patches/net/minecraft/world/chunk/storage/RegionFile.java.patch> to mixins to allow saving&loading chunks with more than 2MB of data in them.

Tested using a new command that can attach random byte arrays of a specified size to items, oversized chunks save and load correctly.

Together with the previous packet size patch this means chunkbans are now a thing of the past :partying_face:

### CODE REVIEW

**Comment by eigenraven** [comment]
Tested in full pack now and it works.

**Comment by boubou19** [comment]
but how does it behave on hybrid servers? Like thermos has it already iirc

**Comment by Caedis** [comment]
The mixin is set to not run when bukkit is detected

**Review by mitchej123 — APPROVED** [review]
yolo

**Pull request merged**
