### PR TITLE
Add server control for fast block placing

### PR DESCRIPTION
**Pull request by Caedis**
Adds server side control for the fast block placing mixin.
If disabled on the server, the mixin is disabled and the keybind will do nothing

Needs testing in game.

### CODE REVIEW

**Comment by Caedis** [comment]
Hmm, can probably use the server config for fastBlockPlacing and then set a flag that the server's was disabled in the sync packet?

**Comment by BlueWeabo** [comment]
What would you mean by that? Isn't that happening already or do you mean having a message for that?

**Comment by Caedis** [comment]
Just thinking out loud mainly. Let me know if there is a better way to do this

**Comment by glowredman** [comment]
Couldn't you simply reuse the same config property?

**Comment by Caedis** [comment]
Going to make a couple changes including changing the color of the overlay text

**Comment by Caedis** [comment]
I am probably just going to rewrite this pr

**Comment by Caedis** [comment]
Will remake this in another PR

**Pull request closed without merging**
