### PR TITLE
Significantly reduce the number of ChunkCoordIntPair allocations

### PR DESCRIPTION
**Pull request by mitchej123**
Tested in the full pack w/ Angelica:

Before:
Note: `func_72903_x - setActivePlayerChunksAndCheckLight`
image

After:
Completely Gone (instead it's now botania's isOreDict :rage: )
image

### CODE REVIEW

**Comment by ah-OOG-ah** [comment]
Why is there still 180 GB? Did you just run it for longer the next time?

**Comment by mitchej123** [comment]
It did run a bit longer.  Not sure why the botania didn't show up before though tbh

**Comment by combusterf** [comment]
> It did run a bit longer. Not sure why the botania didn't show up before though tbh

After reviewing the fix, I can imagine that the delay is very much driver-specific.

**Comment by mitchej123** [comment]
> After reviewing the fix, I can imagine that the delay is very much driver-specific.

The other fix for Botania is unrelated to the memory usage here.  And yes, querying the drivers is very driver specific - nvidia for example uses a thread that requires synchronization thread that tends to bottleneck get** calls

**Comment by mitchej123** [comment]
The botania issue here is related to copying the itemstack to set the damage to check for equality :fail:

**Comment by Dream-Master** [comment]
works for me

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
