### PR TITLE
Add int dimension id to end of login packet

### PR DESCRIPTION
**Pull request by Caedis**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13955

Feel free to come up with a better implementation of this

### CODE REVIEW

**Comment by Caedis** [comment]
Tested with a vanilla server and a forge client with this version loaded and no issues with packet validation

**Review by eigenraven — APPROVED** [review]

**Comment by unilock** [comment]
This change breaks connecting to a Forge 1.7.10 server with Hodgepodge running behind a [Velocity server proxy](https://papermc.io/software/velocity), with the following error in Velocity's logs:

```
[08:40:16] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] <player> -> <server>: exception encountered in com.velocitypowered.proxy.connection.backend.TransitionSessionHandler@10593c18
io.netty.handler.codec.CorruptedFrameException: Packet sent for class com.velocitypowered.proxy.protocol.packet.JoinGamePacket was too big (expected 17 bytes, got 21 bytes)
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleOverflow(MinecraftDecoder.java:112) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:90) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-369.jar:3.3.0-SNAPSHOT (git-c34dafe2-b369)]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

To reproduce:
- Forge 1.7.10 server with [BungeeForge](https://github.com/caunt/BungeeForge), Hodgepodge, [UniMixins](https://github.com/LegacyModdingMC/UniMixins)
- Forge 1.7.10 client with Hodgepodge, UniMixins
- Velocity proxy with [Ambassador](https://github.com/adde0109/Ambassador) and `player-info-forwarding-mode = "legacy"` in `velocity.toml`
- Connect to the server through Velocity, get kicked with nondescript errors on client and server, and the above stacktrace in Velocity

**Comment by Caedis** [comment]
@unilock then disable the config in the settings. We only fully suppose vanilla forge servers due to the changes others make.

**Comment by unilock** [comment]
Sorry, didn't see that it was configurable. Thanks!

**Pull request merged**
