### PR TITLE
Vanilla Fix: Player Sound Registered as Friendly Creatures

### PR DESCRIPTION
**Pull request by Cleptomania**
This fixes a bug in vanilla Minecraft where certain player sounds were registered as animal(AKA friendly creatures) sounds. This caused them to not be played when the friendly creatures sounds were muted.

GTNH Issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11752

Here's a link to the Mojang bug report: https://bugs.mojang.com/browse/MC-36360

The issue has since been fixed in Vanilla minecraft so this is a backport of sorts. The problem is that in the vanilla `sounds.json` file these sounds are registered incorrectly, however you are unable to override this setting via resourcepacks, so a mixin is needed to intercept the sounds loading in, and dynamically change the SoundCategory depending on the name of the sound.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Cleptomania can you run spotless apply to fix build issues ?

**Comment by Cleptomania** [comment]
@Dream-Master I get no changes when running the spotlessApply gradle task

**Comment by Dream-Master** [comment]
yea seems some server was down. re run it now

**Comment by Dream-Master** [comment]
@Cleptomania can you set Gradle version to 1.2.11 ? then it will build

**Comment by Cleptomania** [comment]
I added a commit to update the build script

**Review by minecraft7771 — APPROVED** [review]

**Comment by Dream-Master** [comment]
@Cleptomania how i can test this ingame if it work or not ?

**Pull request merged**
