### PR TITLE
Better volume scaling

### PR DESCRIPTION
**Pull request by Quarri6343**
Minecraft has linear volume scaling so "turn volume to 50%" is not "I can hear 2x quieter".
I have to scale block sound all the way down to like 5% to hear not too loud sound in GTNH.
This PR tries to fix that.
It is exactly what https://modrinth.com/mod/logarithmic-volume-control does but better implementation
It fixes https://bugs.mojang.com/browse/MC-141201

Tested in full pack.
This does not change the max volume.

### CODE REVIEW

**Review by mitchej123 — APPROVED** [review]

**Comment by mitchej123** [comment]
Just making sure -- if we enable this by default, and someone updates, sound will potentially get __quieter__  and not __louder__?  Don't want to jumpscare anyone

**Comment by Dream-Master** [comment]
i got reports the sound much more quit than before.

**Comment by Caedis** [comment]
> Fix Volume Slider is ineffective until reaching the lower end
Could have just been "Logarithmic Volume Slider" imo, but oh well

**Comment by eigenraven** [comment]
This mixin is not logarithmic, you made it quadratic btw.

**Pull request merged**
